-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 18:12:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather` DEFAULT CHARACTER SET utf8 ;
USE `weather` ;

-- -----------------------------------------------------
-- Table `weather`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`payment` (
  `id_payment` INT NOT NULL,
  `indate` VARCHAR(45) NULL DEFAULT NULL,
  `outdate` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_payment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `weather`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`user` (
  `email` VARCHAR(25) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `pw` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `indate` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `weather`.`ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`ad` (
  `id_ad` INT NOT NULL,
  `user_email` VARCHAR(25) NOT NULL,
  `payment_id_payment` INT NOT NULL,
  `ad_title` VARCHAR(45) NULL DEFAULT NULL,
  `ad_url` VARCHAR(45) NULL DEFAULT NULL,
  `ad_image` VARCHAR(45) NULL DEFAULT NULL,
  `ad_price` VARCHAR(45) NULL DEFAULT NULL,
  `ad_location` VARCHAR(45) NULL DEFAULT NULL,
  `indate` VARCHAR(45) NULL DEFAULT NULL,
  `outdate` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ad`, `user_email`, `payment_id_payment`),
  INDEX `fk_ad_user1_idx` (`user_email` ASC) VISIBLE,
  INDEX `fk_ad_payment1_idx` (`payment_id_payment` ASC) VISIBLE,
  CONSTRAINT `fk_ad_payment1`
    FOREIGN KEY (`payment_id_payment`)
    REFERENCES `weather`.`payment` (`id_payment`),
  CONSTRAINT `fk_ad_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `weather`.`user` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `weather`.`cloth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`cloth` (
  `id_cloth` INT NOT NULL,
  `user_email` VARCHAR(25) NOT NULL,
  `temp` VARCHAR(45) NULL DEFAULT NULL,
  `item1` VARCHAR(45) NULL DEFAULT NULL,
  `item2` VARCHAR(45) NULL DEFAULT NULL,
  `item3` VARCHAR(45) NULL DEFAULT NULL,
  `item4` VARCHAR(45) NULL DEFAULT NULL,
  `item5` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cloth`, `user_email`),
  INDEX `fk_cloth_user_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_cloth_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `weather`.`user` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
